In [73]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [61]:
veriseti = pd.read_excel("veri.xlsx") #önce veri dosyasını okutuyoruz.

In [62]:
veriseti 

cinsyet sınıf  gelir
0       k     i   2500
1       e     m   3500
2       e     p   8000
3       e     m   4000
4       k     m   5500
5       k     i   3200
6       e     p  12000
7       k     i   3400
8       k     i   1800

In [63]:
cinsiyet = veriseti.iloc[:,0:1].values #DataFrame objesinden cinsiyet sütununun alıp array objesine dönüştürdük

In [64]:
cinsiyet

array([['k'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['k'],
       ['k']], dtype=object)

In [74]:
le = LabelEncoder() #le objesi binary kategorik değişken olan cinsiyete nümerik değer atıyacak

In [75]:
cinsiyet = le.fit_transform(cinsiyet) #dönüşümü sağladık

In [76]:
cinsiyet

array([1, 0, 0, 0, 1, 1, 0, 1, 1], dtype=int64)

In [77]:
veriseti["cinsiyet2"] = cinsiyet #Cinsiyet değişkenini recode edip yeni sütun oluşturduk

In [78]:
veriseti

cinsyet sınıf  gelir  cinsiyet2
0       k     i   2500          1
1       e     m   3500          0
2       e     p   8000          0
3       e     m   4000          0
4       k     m   5500          1
5       k     i   3200          1
6       e     p  12000          0
7       k     i   3400          1
8       k     i   1800          1

##### Polinomiyal kategorik değişkeni kukla değişkene dönüştürme

In [80]:
sınıf = veriseti.iloc[:,1:2].values #sınıf değişkenini DataFrame'den array tipinde çektik

In [81]:
sınıf

array([['i'],
       ['m'],
       ['p'],
       ['m'],
       ['m'],
       ['i'],
       ['p'],
       ['i'],
       ['i']], dtype=object)

In [82]:
sınıf[:,0] = le.fit_transform(sınıf[:,0]) #sınıf sütununu bir liste olarak değil bir array olarak fonksiyona sokmamız gerekir. Değişkenimizi "sınıf" olarsak alsaydık liste dönerdi. Bu sebeple sınıf[:,0] ifadesini kullandık

In [83]:
sınıf #le fonksiyonumuz etiketleri sayıya çevirdi. Array yapısı bozulmadı.

array([[0],
       [1],
       [2],
       [1],
       [1],
       [0],
       [2],
       [0],
       [0]], dtype=object)

In [84]:
ohe = OneHotEncoder() #ohe objesi kukla dönüşümünü sağlayacak. Esas iş burada başlıyor.

In [85]:
sınıf = ohe.fit_transform(sınıf).toarray() #toarray() metodunu kullanmasaydık kukla değişikenleri demet şeklinde verecekti. Ancak biz array yapısında istiyoruz.

In [86]:
sınıf #şimdi elde ettiğimiz üç kukla değişkeni başlangıçtaki veri setimize monte edeceğiz.

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [88]:
sınıf = pd.DataFrame(data=sınıf, columns=["işçi","memur","patron"]) #array yapısındaki sınıf değişkenini yeniden dataframe'e dönüştürüyoruz.

In [89]:
sınıf

işçi  memur  patron
0   1.0    0.0     0.0
1   0.0    1.0     0.0
2   0.0    0.0     1.0
3   0.0    1.0     0.0
4   0.0    1.0     0.0
5   1.0    0.0     0.0
6   0.0    0.0     1.0
7   1.0    0.0     0.0
8   1.0    0.0     0.0

In [92]:
veriseti = veriseti.join(sınıf) #şimdi de sınıf dataframe'ini başlangıçtaki veriseti dataframe'ine monte ediyoruz. 

In [93]:
veriseti #veriseti'nin son hali.

cinsyet sınıf  gelir  cinsiyet2  işçi  memur  patron
0       k     i   2500          1   1.0    0.0     0.0
1       e     m   3500          0   0.0    1.0     0.0
2       e     p   8000          0   0.0    0.0     1.0
3       e     m   4000          0   0.0    1.0     0.0
4       k     m   5500          1   0.0    1.0     0.0
5       k     i   3200          1   1.0    0.0     0.0
6       e     p  12000          0   0.0    0.0     1.0
7       k     i   3400          1   1.0    0.0     0.0
8       k     i   1800          1   1.0    0.0     0.0

In [94]:
veriseti.to_excel("veri2.xlsx") #yeni veri dosyası oluşturuyoruz

In [ ]:
#işlemimiz burada so